### ISSUE TITLE
Layer not automatically opening for vue files

### ISSUE THREAD

**Issue by RX14** [AdamNiederer/vue-mode#12]
I've installed vue-mode to spacemacs like so, but it doesn't automatically enable when I open a `.vue` file. I have to manually `M-x vue-mode` to get it to work. Do I need to do anything extra to get it to autoload?

```el
     (vue-mode :location (recipe
                          :fetcher github
                          :repo "codefalling/vue-mode"))
```

**Comment by CodeFalling** [comment]
At least you need add 

```
(use-package vue-mode)
```

in your `user-init` if you use `.spacemacs` or `your-private-layer-post-init-vue-mode` if you use a private layer.

**Comment by RX14** [comment]
I thought it would be something similar to that. I had to add the `use-package` to my `dotspacemacs/user-config`. Could you add some docs on installing vue-mode without a private layer to the readme?

**Comment by nickclasener** [comment]
Credits go to @RX14
```
(defun dotspacemacs/user-config ()
  (use-package vue-mode)
)
```

**Comment by AdamNiederer** [comment]
Hello, 

I believe this issue is fixed with [this commit](https://github.com/AdamNiederer/vue-mode/commit/a4d1c353b9aa8809a54737c220c7a9276dad69c0). Let me know if you're having any further issues after updating.
