### ISSUE TITLE
Tab 2 space

### ISSUE THREAD

**Issue by sirsquall** [AdamNiederer/vue-mode#13]
Hello,

How can I set the indentation to 2 space instead of a tab?

Thanks

**Comment by CodeFalling** [comment]
`vue-mode` dosen't handle indent itself. It just combine other modes (for example `javascript-mode`). You can change indent of each mode to make it. Such as  

```emasc-lisp
(setq indent-tabs-mode nil
      js-indent-level 2)
```

to use two space in `javascript-mode`

**Comment by sirsquall** [comment]
Hi,

Thanks you, it's working well for the javascript, and for the web mode? Ho can you indent? 

Thank you

**Comment by CodeFalling** [comment]
See http://web-mode.org/ for documents about indent of `web-mode`.

**Comment by choma** [comment]
I always recommend using [editorconfig](https://github.com/editorconfig/editorconfig-emacs/) to avoid all indentation issues.

Vue templates already includes an .editorconfig file, so you won't have to configure it.

In this case I haven't been able to manage the indentation-offset for scripts and styles (I'm guessing there is some incompatibility between .editorconfig and web-mode). It's a minor issue, but If someone succeeds with this, please comment! :)

**Comment by AdamNiederer** [comment]
Closing old questions; feel free to reopen if you require further assistance.
