### ISSUE TITLE
emmet-mode minor mode as well as web-mode.

### ISSUE THREAD

**Issue by Snorflake** [AdamNiederer/vue-mode#18]
Is there a way to have the emmet-mode activated while web-mode is too? Would make the template writing less painful.

**Comment by sidmitra** [comment]
@Snorflake 
You can enable a mode when another mode is running using hooks.

So for example on web-mode enable emmet mode.
```
(add-hook 'web-mode 'emmet-mode)
```
See https://www.gnu.org/software/emacs/manual/html_node/emacs/Hooks.html

**Comment by AdamNiederer** [comment]
Hello,

`web-mode` actually makes use of the same technology vue-mode uses to do multi-language highlighting, and can override vue-mode and break things. Therefore, it's not the best choice for templates and I'd advise against it.

However, we do have a [specialized vue template major mode](https://github.com/AdamNiederer/vue-html-mode) now, and you may use its hook just like `web-mode`:

```elisp
(add-hook 'vue-html-mode 'emmet-mode)
```
