### ISSUE TITLE
How to install in spacemacs?

### ISSUE THREAD

**Issue by yunhor** [AdamNiederer/vue-mode#20]
When I install vue-mode in spacemacs and reload spacemacs,it will be removed.Would somone tell me how to use vue-mode in spacemacs? Thanks!

**Comment by CodeFalling** [comment]
See https://github.com/syl20bnr/spacemacs/blob/master/doc/FAQ.org#install-a-package-not-provided-by-a-layer

**Comment by AdamNiederer** [comment]
Closing old questions; feel free to reopen if you require further assistance.
