### ISSUE TITLE
Modes don't work

### ISSUE THREAD

**Issue by mohamed-aziz** [AdamNiederer/vue-mode#23]
Hello, I use Emacs 25.1.1 and I have a problem, only css mode works, vue-html-mode and js-mode don't work for me.

**Comment by mohamed-aziz** [comment]
Only works when setting lang actually.

**Comment by AdamNiederer** [comment]
Fixed in #26

**Comment by AdamNiederer** [comment]
I believe this has been fixed in one of the regex-modifying commits since this was filed - please reopen if you're still experiencing problems :)
