### ISSUE TITLE
Readme is very unfriendly for non-spacemacs experts

### ISSUE THREAD

**Issue by Trevoke** [AdamNiederer/vue-mode#24]
The readme needs a little work; I was just a witness to this conversation:

![image](https://cloud.githubusercontent.com/assets/67913/24368722/812e96f6-12ef-11e7-8d42-eb59e11752cc.png)

If your package is the reason people abandon spacemacs, that's a problem :/

**Comment by mohamed-aziz** [comment]
Hey @Trevoke it seems to be a bug related to the new regex changes just fallback to an old commit for now until this is fixed or just use my fork with the old commit.

    (vue-mode :location (recipe
                         :fetcher github
                         :repo "mohamed-aziz/vue-mode"))

**Comment by AdamNiederer** [comment]
Fixed in #26

**Comment by Trevoke** [comment]
I was able to get this user to figure out how to add this package by cobbling pieces together from three other people's problems with this package, which indicates there's room for improvement in the readme.

**Comment by AdamNiederer** [comment]
I'm not very familiar with spacemacs' configuration system, so I'd love some help with this section of the readme. The mode can be installed and then "just work" on vanilla emacs, so I doubt making it work with spacemacs is too crazy.

**Comment by jaysoifer** [comment]
@AdamNiederer I'm on it. Could take about a week or less and I know it will need refining but, hey, at least is something.

@Trevoke if you can share those links (assuming you still remember / have access to them), I'm collecting "best practices".

**Comment by Trevoke** [comment]
Here is the archive of the conversation:
https://elixir-lang.slackarchive.io/emacs/page-16/ts-1490514044128594

I can't promise best practices, as I am not a spacemacs user.

**Comment by jaysoifer** [comment]
@Trevoke @AdamNiederer done. Comments are appreciated 😃
