### ISSUE TITLE
Where is the package and package.el files?

### ISSUE THREAD

**Issue by raultrysw** [AdamNiederer/vue-mode#29]
Hello, I am begining to spacemacs and me would like to use in my projects. But i dont find the files that are named in the readme in the github home project.
Could you help me please? =)

**Comment by CodeFalling** [comment]
In your private layer in fact. If you use spacemacs without private layer, you should just add it to your `.spacemacs`.

**Comment by raultrysw** [comment]
What have i to write in .spacemacs? Where should I create that file? In the home directory?

**Comment by CodeFalling** [comment]
Read spacemacs's document here: http://spacemacs.org/doc/FAQ.html#install-a-package-not-provided-by-a-layer

**Comment by raultrysw** [comment]
Sorry, I don't know what does that link with my question :(

**Comment by raultrysw** [comment]
Also I know nothing about either lisp nor elisp :(

**Comment by raultrysw** [comment]
Please, help :(

**Comment by CodeFalling** [comment]
`vue-mode` is a package from ELPA which is not provided by a spacemacs layer. [This document]( http://spacemacs.org/doc/FAQ.html#install-a-package-not-provided-by-a-layer) is about how to include package in spacemacs.

**Comment by nickclasener** [comment]
@raultrysw 
Add this to .spacemacs to get there spc->f->e->d
```
(vue-mode :location (recipe
                                  :fetcher github
                                  :repo "codefalling/vue-mode"))
```
to your
```
 dotspacemacs-additional-packages '()
```

**Comment by AdamNiederer** [comment]
Closing old questions; feel free to reopen if you require further assistance
