### ISSUE TITLE
缩进失败

### ISSUE THREAD

**Issue by Qquanwei** [AdamNiederer/vue-mode#30]
当我在这个位置tab时候
![image](https://cloud.githubusercontent.com/assets/9263655/24988972/db16c8a6-203b-11e7-9fca-55e806177574.png)

结果emacs提示错误信息
![image](https://cloud.githubusercontent.com/assets/9263655/24988980/eb296a00-203b-11e7-8a5e-0f0c0869d978.png)

**Comment by Qquanwei** [comment]
会不会是因为没有安装`js-mode`导致的?

**Comment by AdamNiederer** [comment]
Hi there,

I'm using a machine translator, so apologies if I missed anything.

It looks like we may need to set something we're not setting at the moment. Is this affecting your ability to write code, or is it just a message?

`js-mode` should be installed on every version of emacs by default. If typing `M-x js-mode` works, then you have it installed.

**Comment by AdamNiederer** [comment]
Our indentation system has changed significantly since this issue was filed, so this shouldn't crop up anymore. If you're still running into issues, feel free to re-open this issue or file another one.

**Comment by YangJie6020** [comment]
> Hi there,
> 
> I'm using a machine translator, so apologies if I missed anything.
> 
> It looks like we may need to set something we're not setting at the moment. Is this affecting your ability to write code, or is it just a message?
> 
> `js-mode` should be installed on every version of emacs by default. If typing `M-x js-mode` works, then you have it installed.

Thanks,  this answer have solve my problem. 

Vue-mode  is great,   good job!!
