### ISSUE TITLE
script with lang="ts" does not work

### ISSUE THREAD

**Issue by ppasieka** [AdamNiederer/vue-mode#33]
In project with where I use typescript as a language in script tag this mode does not work.

![image](https://user-images.githubusercontent.com/2170707/27303070-c7b9ec42-5539-11e7-9345-65d55878de8f.png)

**Comment by AdamNiederer** [comment]
We currently look for `<script lang="typescript">`. A full list of names can be found here (after the `:name` keyword). We should probably document this better.

https://github.com/CodeFalling/vue-mode/blob/master/vue-mode.el#L41

**Comment by ppasieka** [comment]
Ok. Thanks

It means that it is enough to just add ` (:type script :name ts :mode typescript-mode)` and it should work, I guess.

BTW It might be a good idea to add `lang="ts` to vue-mode. A lot of code examples I've seen on github uses short version

**Comment by AdamNiederer** [comment]
Added in e256f43. Feel free to re-open if you experience any further difficulties or have any questions.
