### ISSUE TITLE
Slim Support

### ISSUE THREAD

**Issue by natsumi** [AdamNiederer/vue-mode#36]
It would be nice to have support for slim as a template language

**Comment by AdamNiederer** [comment]
Slim templates look like a Ruby thing - are they supported by the vue template compiler?

As a stopgap, you may customize `vue-modes` by adding the following element after installing `slim-mode`:

```elisp
 (:type template :name slim :mode slim-mode)```

**Comment by natsumi** [comment]
@AdamNiederer 
Slim template support is native with the vue webpack loader.  The webpack loader is slm though.

I had to set 
```
(:type template :name slm :mode slim-mode) 
```

And that works.  As soon as I open my .vue file it correctly recognizes the template block.  However the color highlighting isn't the same as when I'm in normal slim-mode.

The block is correctly recognized as vue[vue-html]
 
Any thoughts on why the highlighting would be off?

Thanks for your help.

**Comment by AdamNiederer** [comment]
Looks like it's still loading vue-html-mode. The block should have vue[Slim] in its modeline.

I added the above string to my `vue-modes` and it looks like slim templates are working. The template on Slim's webpage has the same highlighting under both vue-mode and slim-mode.

Reset your customization and pull vue-mode from melpa once it builds e256f432. `<template lang="slim">` and `<template lang="slm">` should work out of the box.

**Comment by natsumi** [comment]
@AdamNiederer works perfect.  Thanks for the help.
