### ISSUE TITLE
Not enabling jit-lock.

### ISSUE THREAD

**Issue by ColMugX** [AdamNiederer/vue-mode#42]
Hey.

I am spacemacs beginner. Now i am having a problem.

It tell me 'not enabling jit-lock: it does not work in indirect buffer'

How can i do?

**Comment by ColMugX** [comment]
And how can i use html auto complete with vue-mode?

**Comment by AdamNiederer** [comment]
I believe the jit-lock issue is a problem with mmm-mode. Could you describe the issue in more detail and file an issue with them? https://github.com/purcell/mmm-mode

For HTML autocompletion, you will need to set up company and a company backend for html. I'm not aware of any HTML autocompletion backends for company, but [here's](https://github.com/AdamNiederer/vue-mode/issues/32#issuecomment-315915012) how to set company up globally for vue-mode if you find one

**Comment by ColMugX** [comment]
OK. thx for your answer.

And i known the issue with mmm-mode in created this issue until 2 hours later. 

I thought about it, or i can't use emacs well. loool.

**Comment by ColMugX** [comment]
EXCUSE ME! Guy!

I found that i can't use autocompletion on vue-mode at all. not only html.

is it my mistake?

**Comment by AdamNiederer** [comment]
Do you have company mode enabled globally?

**Comment by ColMugX** [comment]
@AdamNiederer 

Yes! I do it!

**Comment by AdamNiederer** [comment]
I have a feeling that this is a configuration or documentation issue rather than one of code. Make sure company-mode is actually enabled, and TAB is appropriately proxied to company-indent-or-complete-common. Spacemacs might interfere with that somehow. If it is, then make sure your company backends are working.

**Comment by ColMugX** [comment]
Thx. 
I try it.
