### ISSUE TITLE
Consider adding edit-indirect functionality

### ISSUE THREAD

**Issue by blaenk** [AdamNiederer/vue-mode#47]
For now this package went with the mmm-mode route but I figured I'd bring up an idea for a potentially more robust and flexible approach to single-file components in vue.

As many people are aware, mmm-mode is pretty hacky and often leads to weird glitches with certain modes. The end result is something that's not quite there for each of the modes. You end up losing out on the major modes and their more robust/comprehensive associated configuration.

I was thinking another approach might be to use something like [edit-indirect](https://github.com/Fanael/edit-indirect).

In case you're not familiar, it lets you basically spawn a new/separate buffer which is actually backed by a _region_ of another pre-existing buffer. So for example you might have a markdown-mode buffer, then you can spawn an indirect buffer of the region within a particular markdown codeblock so that now you have a separate buffer containing only that region, such that when you save that buffer those changes are committed back to the original markdown buffer. The real benefit of doing this is that since it's an entirely separate buffer you can then enable another mode such as emacs-lisp-mode (assuming the codeblock contained elisp code) in order to fully leverage emacs-lisp-mode configuration, keybinds, syntax highlighting, etc., all while still editing the same original buffer.

First, the buffer of the `.vue` file itself would be opened, then an edit-indirect buffer/window would be created for each section of the vue file. To make sure there's room we could save the window configuration prior to doing this, so that we have the entire frame to ourselves. Then we'd stack the edit-indirect buffer windows in the same order as they appear in the vue file. This would give us full-fledged buffers for each of the sections, with major modes corresponding to that section.

In fact, we can even go further so that for example if a `<style>` section's `lang` is set to `jade` then the edit-indirect buffer would use pug-mode. There would be sensible defaults for the most common ones and a defcustom alist which the user can use to map a lang attribute value to the corresponding mode they'd like to use, or otherwise fundamental-mode would be used as a fallback (or whatever). This is similar to what markdown-mode does.

It need not be an all-or-nothing ordeal. We can also keep the current setup of using mmm-mode for a birds-eye view of the entire file and perhaps quick edits, and then we can register a keybind so that if we trigger it while over a specific section it would edit-indirect only that section. This is similar to what markdown-mode does for codeblocks. There could also be a separate keybind which would do a full spawning of edit-indirect buffers for each section as described above.

I think this would be the best way to bridge the gap between multiple environments in one file and being able to fully utilize each powerful mode for each section, while still editing the same file.

**Comment by AdamNiederer** [comment]
Hello,

Thank you for such an in-depth write-up. Edit-indirect functionality looks like a fantastic addition to vue-mode. I'll implement this as soon as I get a free moment.

**Comment by blaenk** [comment]
No problem, thanks for being open to the idea. I noticed after the fact that I was kind of all over the place, so if you need clarification on anything, feel free to ask!

**Comment by blaenk** [comment]
Also I forgot to mention, I was describing this feature in terms of functionality that markdown-mode provides for codeblocks, but it actually was inspired by org-mode. I don't use org-mode myself, however, so I can't comment further, but I do know that it (and markdown-mode) support both:

* fontifying a region of a buffer with an arbitrary mode (without using mmm-mode; you can see [here](https://github.com/jrblevin/markdown-mode/blob/7050c4d6f160694570c2d1868ddad9a67bb97dd6/markdown-mode.el#L8743) markdown-mode's code adapted/inspired by org-mode's)
* spawning an "edit-indirect" buffer from that region if the user wants a full-fledged buffer with the mode they want enabled (you can see markdown-mode's code for that [here](https://github.com/jrblevin/markdown-mode/blob/7050c4d6f160694570c2d1868ddad9a67bb97dd6/markdown-mode.el#L8780)).

**Comment by AdamNiederer** [comment]
Added in b3b2649.

I had to use one work-around to prevent edit-indirect from killing the overlays set by mmm-mode, but it works really well otherwise. Thanks a lot for the suggestion! Feel free to open another issue if you'd like to see anything else added :)

**Comment by blaenk** [comment]
Awesome, great work! 👍 I'll have to try it next time I get a chance.
