### ISSUE TITLE
First line in <script> tags indented differently

### ISSUE THREAD

**Issue by tomatopeel** [AdamNiederer/vue-mode#50]
Hey,

I'm getting this behaviour where the first line within the `<script>` tags of any .vue file with vue-mode[JavaScript] enabled is indenting the first line with one more indent than the rest of the lines:

![test_1](https://user-images.githubusercontent.com/13825174/30656368-2e0a954e-9e34-11e7-8223-e87f73597620.gif)

`indent-line-function` is `mmm-indent-line` but if I manually execute `js-indent-line` the behaviour is the same.

**Comment by AdamNiederer** [comment]
Hello,

Thanks for your report. I've experienced this issue as well, and have a fix in mind. I'll try to get it pushed up as soon as I have a free moment.

**Comment by AdamNiederer** [comment]
Sent a patch: https://github.com/purcell/mmm-mode/pull/74

After this is accepted, I'll need to add a line in `vue-initialize` to use this new function. I'll also need to synchronize with mmm-mode for the next stable release.

**Comment by dgutov** [comment]
Regardless of whether that patch is accepted, you can include it in `vue-mode` in the meantime, right? I'm just guessing that you're going to want to further tweak that function, specifically for Vue syntax.

**Comment by AdamNiederer** [comment]
Apologies for the extremely long wait; I've decided to abandon merging the utility functions upstream and have just added them locally. This should be fixed now.

**Comment by sprhawk** [comment]
Why is mine still wrong for first line under script?
```
<template>
<div id='app'>
</div>
</template>

<script lang="ts">
    
    import Vue from 'vue'

export default Vue.extend({
    components: {
    },
    methods: {
    },
});

</script>

<style lang='scss' scoped>
  .canvas {
  width: 100%;
  height: 100%;
  }
</style>

<style lang='scss'>
  
html,body {
    overflow: hidden;
    width: 100%;
    height: 100%;
    margin: 0;
    padding: 0;
}

</style>
```
