### ISSUE TITLE
Add support for MIME types

### ISSUE THREAD

**Issue by troglotit** [AdamNiederer/vue-mode#51]
Syntax highlighting breaks when script tag(or maybe anything else) has specified MIME type like this:
![image](https://user-images.githubusercontent.com/10955264/30810024-56d4aa2e-a20c-11e7-9309-61a16707efb9.png)
That is not necessary in script tag from Vue point of view, it was added because of Webstorm IDE (syntax highlighting breaks for it without specified MIME type). Sure, fixing deficiencies of another editors and paid IDEs(!) is kinda ridiculous, but, alas, emacs-users are in minority.

I made it to work for myself in https://github.com/AdamNiederer/vue-mode/blob/master/vue-mode.el#L84 replacing space by dot at 47th position. If it doesn't conflict with Vue specs, maybe we're able to add it?

**Comment by AdamNiederer** [comment]
Fixed via ed997fe
