### ISSUE TITLE
Indent size of 4 while editorconfig tells 2

### ISSUE THREAD

**Issue by bersace** [AdamNiederer/vue-mode#52]
Hi,

Thanks for vue-mode and vue-html-mode :-) I'm using spacemacs and I like the idea of `.vue` file to embed all languages for one component.

The first issue I encouter is that while `template` tag is properly indented with 2 spaces, `script` and `style` have 4 spaces identations.

My `.editorconfig` is the one from vue template:

```
root = true

[*]
charset = utf-8
indent_style = space
indent_size = 2
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
```

My `.spacemacs` stanza is:

``` lisp
   dotspacemacs-additional-packages
   '(
    (vue-mode :location (recipe
                          :fetcher github
                          :repo "codefalling/vue-mode"))
     )
...
 (defun dotspacemacs/user-init ()
  (require 'company)
  (global-company-mode)
  (global-set-key (kbd "TAB") #'company-indent-or-complete-common)

  (require 'vue-mode)
  (add-to-list 'company-backends 'company-tern)
  (add-hook 'js-mode-hook #'tern-mode)
  (add-to-list 'vue-mode-hook #'tern-mode smartparens-mode)
  (setq mmm-js-mode-exit-hook (lambda () (setq tern-mode nil)))
  (setq mmm-js-mode-enter-hook (lambda () (setq tern-mode t)))
  )
```

I wish i can help more !

**Comment by AdamNiederer** [comment]
Hello,

Thanks for your interest in vue-mode. Could you include a minimal sample which demonstrates this behavior? I think this might be related to #50.

**Comment by bersace** [comment]
@AdamNiederer Do you have a hint on how to create a seperata minimal sample ? I guess you want a `.spacemacs` and a sample file ?

**Comment by bersace** [comment]
If I reindent buffer i get the following output:

``` html
<template>
  <div class="hello">
    <p>{{ msg }}</p>
  </div>
</template>

<script>
    export default {
        name: 'hello',
        data () {
            return {
                msg: 'Welcome to Your Vue.js App'
            }
        }
    }
  </script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
h1, h2 {
      font-weight: normal;
  }

  ul {
      list-style-type: none;
      padding: 0;
  }

  li {
      display: inline-block;
      margin: 0 10px;
  }

  a {
      color: #42b983;
  }
  </style>
```

**Comment by bersace** [comment]
Ok, I'm working on a .spacemace reproduction with `HOME=~/isolated emacs`

**Comment by bersace** [comment]
Here is the `.spacemacs`:

``` lisp
   dotspacemacs-configuration-layers
   '(
     helm
     emacs-lisp
     html
     )
   dotspacemacs-additional-packages
   '(
     editorconfig
     (vue-mode :location (recipe
                          :fetcher github
                          :repo "codefalling/vue-mode"))
     )
```

**Comment by AdamNiederer** [comment]
I can't reproduce this issue. Could you tell me the value of `js-indent-level` (in vanilla emacs, type `C-h v js-indent-level RET`)?

**Comment by bersace** [comment]
@AdamNiederer *Its value is 4*.

`.editorconfig` is:

```
root = true

[*]
charset = utf-8
indent_style = space
indent_size = 2
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
```

According to `editorconfig-find-current-editorconfig`.

**Comment by AdamNiederer** [comment]
Change it to 2 and see try again?

**Comment by bersace** [comment]
@AdamNiederer thanks. I didn't find anything related on Great Google :/

**Comment by AdamNiederer** [comment]
No problem. Feel free to file another issue if something else crops up :)

**Comment by bersace** [comment]
Hi,

Thanks for the hints. I'm workaround this with `.dir-locals.el`:

``` lisp
((js-mode . (js-indent-level . 2))
 (css-mode . (css-indent-offset . 2)))
```

**Comment by algking** [comment]
M-x add-dir-local-variable will help
