### ISSUE TITLE
Change background

### ISSUE THREAD

**Issue by Luummii** [AdamNiederer/vue-mode#61]
Hello! I am emacs beginer!
How change background in emacs?
This method dont work for me.

(defun vue-mode/init-vue-mode ()
  (use-package vue-mode
               :config
               ;; 0, 1, or 2, representing (respectively) none, low, and high coloring
               (setq mmm-submode-decoration-level 0)))

**Comment by AdamNiederer** [comment]
If you're looking to change the global background color, look at `set-background-color`. For example:

```elisp
(set-background-color "#2f343f")
```

Put that in your init file `~/.emacs.d/init.el`.

**Comment by Luummii** [comment]
This change is global. But in file .vue is no change, between tags <template></template> and <script></script>

**Comment by jaysoifer** [comment]
damn @AdamNiederer you need someone to help you with the whole spacemacs thing. I admire your patience with us.

**Comment by AdamNiederer** [comment]
It's no problem - Sorry I haven't made much progress on those bugfixes in the past few weeks. Schoolwork and interviews have stolen most of my time.

@Luummii Could you try customizing `mmm-default-submode-face`? That's the background for each submode when the default configuration is used.

**Comment by Luummii** [comment]
I am so sorry! I cant make this customizing! I am beginner emacs. But I very want learning this product! I am worker vuejs development and want refuse VSCode. How customizing mmm-default-submode-face? Tell me please!
