### ISSUE TITLE
Add seperate major modes for indirect buffers

### ISSUE THREAD

**Issue by AdamNiederer** [AdamNiederer/vue-mode#64]
As discussed in #48, there should be an easy way to specify substitute major modes for indirect buffers. For example, substituting js-mode for js2-mode seems like a popular request.

**Comment by Snorflake** [comment]
https://github.com/phillord/lentic could be useful

**Comment by AdamNiederer** [comment]
Resolved in cb70a5a571864c47490244ecef2b2071d248abe4
