### ISSUE TITLE
Problems with indentation on sass mode

### ISSUE THREAD

**Issue by am** [AdamNiederer/vue-mode#66]
Using sass I've a ugly problem that prevents me from yank any code into the file, since it messes with the indentation of the all block. Here is how to reproduce:
On a file.vue
```vue
<style lang="sass" scoped>
$foo: 1
$bar: 2
.neat-block
  display: block
  $
</style>
```
cursor is at the last `$`, when yanking a new line, say `width: 10vw` it will end up like this:
```vue
<style lang="sass" scoped>
  $foo: 1
    $bar: 2
      .neat-block
        display: block
  width: 10vw
</style>
```
Tried to run `vue-mode-reparse` right before yanking, but I got the same result. 
What solves this issue is to change to `sass-mode`, yanking does not introduces issues there, but obviously is far from practical to keep changing modes inside a vue file.

Any thoughts?

**Comment by AdamNiederer** [comment]
Hello,

Thanks for the report, and thanks for such a detailed repro case. I've added a fix to ssass-mode which should fix the underlying issue (a95c4c9f99895cc582849b35e90ae13f1587ddce). Could you give that a shot once MELPA builds it?

**Comment by am** [comment]
It looks good @AdamNiederer !

Only thing I noticed is some whitespace added between classes declarations, example:
```vue
<style lang="sass" scoped>
.neat-block
  display: block

.other-block
  display: block
  $
</style>
```
After yank it ends up with some whitespace:
```vue
<style lang="sass" scoped>
.neat-block
  display: block
·· // < there
.other-block
  display: block
  width: 10vw$
</style>
```
To be quite honest it's something that don't affect me that much since I cleanup whitespace on save, just to let you know.

Many thanks for the fix, this was annoying =P

**Comment by AdamNiederer** [comment]
No problem. I'm going to close this and re-file that whitespace issue under the ssass-mode repo. Feel free to re-open or file another issue if you have any further questions or troubles.
