### ISSUE TITLE
web-mode reloading changes mode off vue-mode

### ISSUE THREAD

**Issue by ar1a** [AdamNiederer/vue-mode#68]
```
<template>
<a></a>
</template>
```

with everything parsed correctly, put cursor inside the template and press C-c C-r (web-mode-reload). It swaps the major mode to web-mode.

Can we block this somehow? without it, there's no highlighting etc.

**Comment by AdamNiederer** [comment]
That'd probably be a lot easier for the web-mode guys to prevent - try filing an issue with them. It should be a quick fix (check for mmm-mode, and abort if it's the primary mode) in their code.
