### ISSUE TITLE
vue-mode doesn't work

### ISSUE THREAD

**Issue by nholiphant** [AdamNiederer/vue-mode#73]
I'm using a mac, installing vue-mode with Melpa and no matter the version of emacs I can't get vue-mode to work reliably. When I run vue-mode-reparse I get:

MMM-ifying buffer...
mmm-get-local-variables-list: Symbol’s function definition is void: mapcan

**Comment by nholiphant** [comment]
A work-around: If I install the multi-web-mode package vue-mode works properly, however if I restart emacs it won't work unless I delete and re-install multi-web-mode.

**Comment by AdamNiederer** [comment]
Hi, thanks for the report.

Could you list your versions of `mmm-mode`, `vue-mode`, and emacs?

**Comment by moaxey** [comment]
I am experiencing the same problem / workaround...

 multi-web-mode     20130823.2054
 mmm-mode           0.5.5
vue-mode           20180104.1611
GNU Emacs 25.3.1

**Comment by nholiphant** [comment]
Thanks Adam, I'm using the same versions of the software as Matthew, I also
tried Emacs 24.5 with the same result.

**Comment by AdamNiederer** [comment]
Hm, it looks like the maintainers of `mmm-mode` took down their MELPA version and have moved their repository to ELPA exclusively. The ELPA version contains un-namespaced versions of emacs' common lisp functions.

As a quick fix:

- Type `C-h f mmm-get-local-variables-list`
- Click the hyperlink to `mmm-region.el`
- Perform the following commands:
- `C-x h`
- `M-x replace-string RET mapcan RET cl-mapcan RET`
- `C-x h`
- `M-x replace-string RET caddr RET cl-caddr RET`
- `C-x h`
- `M-x replace-string RET cadddr RET cl-cadddr RET`
- `M-x byte-compile-file`

In the byte-compilation output, no missing function warnings should display.

I'd recommend filing an issue against mmm-mode for this, as they definitely shouldn't be shipping a package with un-namespaced cl functions.

**Comment by nholiphant** [comment]
Thanks Adam, the fix worked for me. I filed an issue with mmm-mode. BTW,
vue-mode is great.

**Comment by AdamNiederer** [comment]
It looks like mmm-mode has released my fixes, so I'm going to close this. Feel free to re-open or file another issue if you encounter any more issues.
