### ISSUE TITLE
Won't parse lang if enclose in single quotes

### ISSUE THREAD

**Issue by josemotanet** [AdamNiederer/vue-mode#76]
Hello, Adam. I've been using vue-mode for quite some time, awesome stuff :+1: 

Consider the following snippet:

```html
<template lang="pug"> ✓
...
<template lang='pug'> ×
```

vue-mode won't detect the language if you enclose the attribute's value in single quotes.

* * *

This might be the place to look for a change but I'm not much of a Lisp guy (yet): https://github.com/AdamNiederer/vue-mode/blob/b489a63dabe0f2fee2730121ecabb1b4f4c11761/vue-mode.el#L133

**Comment by AdamNiederer** [comment]
Hey, thanks for the thorough report. It looks like emacs doesn't highlight single quotes around attributes, but they are [allowed by w3](https://www.w3.org/TR/html4/intro/sgmltut.html#h-3.2.2).

I've pushed e3c252ae42be391d1bb1653c4e21091b21d2dfc4, which should resolve your issue. Try it out when MELPA rebuilds, and feel free to re-open this or file another issue if you experience any further problems.

**Comment by josemotanet** [comment]
Thank you Adam. I'm glad I could be of use. Have a great day! :+1:

**Comment by josemotanet** [comment]
Just confirmed that the update works like a charm. Thank you Adam for your attentiveness.
