### ISSUE TITLE
`vue[CSS]` not detected when using attributes like `scoped` or `lang`

### ISSUE THREAD

**Issue by geowa4** [AdamNiederer/vue-mode#78]
# Actual
When using bare tags `<style></style>`, the mode `vue[CSS]` is detected. When adding an attribute, parsing fails. For instance, `<style scoped></style>` fails.

# Expected
`<style scoped></style>` works identically to `<style></style>` in Emacs.

# Notes
Additionally, adding the `lang` attribute for using Stylus also breaks it the same way. I'm not sure if supporting other CSS variants is in scope of this issue or if you'd like to handle that in a separate issue.

**Comment by AdamNiederer** [comment]
Both of these snippets work for me. Could you post your installed versions of `emacs`, `vue-mode`, `mmm-mode`, and provide a snippet which doesn't work for you? Thanks.

```vue
<style scoped>
.looks-fine-to-me {
    color: red;
}
</style>

<style lang="sass" scoped>
.looks-fine-to-me
  color: red
</style>
  
```

**Comment by geowa4** [comment]
I can no longer reproduce this issue myself.
