### ISSUE TITLE
Why not web-mode?

### ISSUE THREAD

**Issue by Compro-Prasad** [AdamNiederer/vue-mode#80]

**Comment by AdamNiederer** [comment]
`web-mode` is less specialized and has less adaptable support for multilanguage buffers. It's the same reason one wouldn't use stock lisp-mode to write clojure.

**Comment by Compro-Prasad** [comment]
There are some engines in `web-mode`. Aren't they sufficient?

**Comment by AdamNiederer** [comment]
I'm sure there's a way to configure web-mode to work with vue template files, but `vue-mode` offers a specialized experience which works out of the box. I'd also argue that the methods used to provide the functionality in `vue-mode` are much less intrusive and prescriptive than those found in `web-mode`.

**Comment by Compro-Prasad** [comment]
What is the specialized experience?

**Comment by AdamNiederer** [comment]
I'm closing this question because of inactivity. Feel free to re-open this issue or start another one if you have further questions.

**Comment by trev-dev** [comment]
I mean no offense to @AdamNiederer when I say that emac's `lsp-mode` + vls work really well together without the need for `mmm-mode` (and subsequently vue-mode).

If anyone here needs to ask "why not web-mode?"; I say in response: "Why vue-mode if you want web-mode?"

You can create a derived mode from web-mode yourself. This ends up being much more simple than vue-mode (again, no offense)

Here's how I do it:

Run `npm i -g vls` first and make sure you have a language server to work with. Then:

```elisp
;; Create a derived mode from web-mode
(define-derived-mode vue-mode web-mode "VueJS"
 "Extend web-mode to .vue files")
(provide 'vue-mode)
(add-to-list 'auto-mode-alist '("\\.vue\\'" . vue-mode))

:; Make lsp mode kick in with vue-mode
(use-package lsp-mode
  :init
  (setq lsp-keymap-prefix "C-c l")
  :hook ((vue-mode . lsp))
  :commands lsp)
```
