### ISSUE TITLE
tab-always-indent doesn't work

### ISSUE THREAD

**Issue by jeremyjh** [AdamNiederer/vue-mode#82]
In Spacemacs (vim bindings enabled) in both the template and script tags, pressing the tab key does nothing at all in, even when indentation is needed `tab-always-indent` is set to t. Other modes (such as rjsx/js2) work fine.

**Comment by AdamNiederer** [comment]
I can't reproduce this issue with a fresh install of spacemacs; do you have any additional configuration atop stock spacemacs?
