### ISSUE TITLE
Auto closing pairs.

### ISSUE THREAD

**Issue by piq9117** [AdamNiederer/vue-mode#87]
Auto closing of brackets, parenthesis, single/double quotes, and back ticks.

I have something locally, do you want me to send a PR?

**Comment by AdamNiederer** [comment]
I'm pretty sure you can do this with [smartparens](https://github.com/Fuco1/smartparens). I'm not sure if I'd like vue-mode to duplicate this feature. Could you detail what you've done to get it working?

**Comment by piq9117** [comment]
thats true. 

i just added
```
(electric-pair-mode 1)
```
