### ISSUE TITLE
script tag indents everything at column 0

### ISSUE THREAD

**Issue by bhanuvrat** [AdamNiederer/vue-mode#97]
It has been working flawlessly for last whole year, and just yesterday stopped formatting script tag properly.
Contents are recognized as javascript, but executing `indent-region` makes it move every line to column zero. :(

![image](https://user-images.githubusercontent.com/499894/66268655-2d3bb100-e85d-11e9-9551-50017cdfa9ae.png)

**Comment by bhanuvrat** [comment]
got this from https://github.com/AdamNiederer/vue-mode/issues/74#issuecomment-528560608

works for me.

(setq mmm-js-mode-enter-hook (lambda () (setq syntax-ppss-table nil)))
(setq mmm-typescript-mode-enter-hook (lambda () (setq syntax-ppss-table nil)))

**Comment by lzhoucs** [comment]
Ran into the same issue on 26.3. No issue on 26.2 for a long time. https://github.com/AdamNiederer/vue-mode/issues/74#issuecomment-539711083
